name: "Hello World"

on:
  push

env:
  TEST_1: HELLO_1
  TEST_2: ${{ vars.TEST_E }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: test
      url: https://github.com
    steps:
    - name: Echo ACCESS_ID
      run: |
        echo ${{ env.TEST_1 }}
        echo ${{ vars.TEST_E }}
        echo ${{ env.TEST_2 }}
        
