name: "Hello World"

on:
  push

env:
  TEST_1: HELLO_1
  TEST_2: ${{ vars.TEST_E }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: test
      url: https://github.com
    steps:
    - name: Echo ACCESS_ID
      run: |
        echo "TEST_1 = ${{ env.TEST_1 }}"
        echo "TEST_E = ${{ vars.TEST_E }}"
        echo "TEST_2 (from TEST_E) = ${{ env.TEST_2 }}"
        
